#!/bin/sh
# populate the metadata cache for portage

command -v emerge > /dev/null 2>&1 && {
	printf '%b' " \033[32;1m*\033[m populating portage cache"
	emerge --metadata || printf '%b' " \033[31;1m!\033[m emerge --metadata failed\n"
}
