keys:
  - &lutea age1p55em5e3uk3fprj2mpum7ulrslcqgly63pjsyw2yv6hx99trdsnsvvv9ex
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age:
      - *lutea
  - path_regex: secrets/lutea.yaml$
    key_groups:
    - age:
      - *lutea
