#!/bin/sh
# generate cache for repositories that don't come with a cache

repo_name=$1
command -v egencache > /dev/null 2>&1 && [ -n "$repo_name" ] && {
	# Gentoo already has it's cache generated
	[ "$repo_name" = "gentoo" ] && exit 0
	printf '%b' " \033[32;1m*\033[m generating cache for $repo_name\n"
	egencache --update --repo "$repo_name" --jobs 4 || \
		printf '%b' " \033[31;1m!\033[m egencache failed\n"
}
