#!/bin/sh
# Some applications (namely java apps) get the home directory from /etc/passwd meaning that
# we can't easily prevent these apps from writing in the home directory by changing the HOME env
# var. Use bubblewrap to bind a random directory to /home/$USER instead.

# Make sure we have a command to execute
[ "$*" ] || {
	printf '%s\n' "Missing command to execute" 1>&2
	exit 1
}

# If HOMEWRAP_HOME isn't set, make our own and ensure that it exists
: "${HOMEWRAP_HOME:=${XDG_STATE_HOME:-$HOME/.local/state}/homewrap/default}"
mkdir -p "$HOMEWRAP_HOME"

# Create sandbox with temporary home
# This breaks if there is a broken symlink in the directory
args="--dev-bind / / --dev-bind $HOMEWRAP_HOME $HOME "

# Recreate the home directory
for i in "$HOME/"* "$HOME/".*
do
	case $i in
		"$HOME/."  ) continue ;;
		"$HOME/.." ) continue ;;
	esac
	args="${args}--dev-bind $i $i "
done

# shellcheck disable=SC2086
exec bwrap $args "$@"
