#!/bin/sh

# Steam allows account switching now
# case $1 in
# 	b|blanklily ) S_HOME="blanklily"; shift ;;
# 	c|crazykill_97 ) S_HOME="crazykill_97"; shift  ;;
# 	* ) S_HOME="blanklily" ;;
# esac

export HOMEWRAP_HOME="${XDG_STATE_HOME:-$HOME/.local/state}/homewrap/valve"
[ -d "$HOMEWRAP_HOME" ] || mkdir -p "$HOMEWRAP_HOME"

[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/Steam/bootstrap.tar.xz" ] \
	&& rm -f "${XDG_DATA_HOME:-$HOME/.local/share}/Steam/bootstrap.tar.xz"

export SDL_VIDEODRIVER=x11
exec homewrap /usr/bin/steam "$@"
