#!/bin/sh
# Start new logging directory
# moulog -n

# Pick Wayland Compositor
case $1 in
	wayfire|w )
		export QT_QPA_PLATFORMTHEME=gnome
		export XDG_CURRENT_DESKTOP=Wayfire
		export XDG_SESSION_TYPE=wayland
		# exec moulog -N compositor dbus-run-session wayfire ;;
		exec dbus-run-session wayfire ;;
esac
