#!/bin/sh
# Post startup script for wayland compositors

# TODO: find a more standard way to autostart applications
# https://wiki.archlinux.org/title/XDG_Autostart
# https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html

# # Dbus (atleast with elogind) doesn't get updated environment variables causing
# # some applications (like mako) to not autostart.
# # moulog -N dbus-env dbus-update-activation-environment --all --systemd &
# dbus-update-activation-environment --all --systemd &

# # Configure displays
# # moulog -N output-manager kanshi &
# kanshi &

# # Set idle actions
# swayidle timeout 900 swaylock &

# # Set a wallpaper
# # moulog -N wallpaper swaybg \
# # 	-i "${HOME}/misc/syncthing/media/images/wallpapers/dark/evie-s-Pb1KFv4tauY-unsplash.jpg" \
# # 	-m fill &
# swaybg \
# 	-i "${HOME}/misc/syncthing/media/images/wallpapers/dark/evie-s-Pb1KFv4tauY-unsplash.jpg" \
# 	-m fill &

# # Nightlight
# # moulog -N blue-light-filter wlsunset -l 33.9 -L -84.5 &
# wlsunset -l 33.9 -L -84.5 &

# # Syncthing
# # moulog -N sync syncthing -no-browser &
# syncthing -no-browser &

# # Panel
# moulog -N panel waybar &
# waybar &
