snippet_support = true
verbosity = 2

[server]
timeout = 1800

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"
settings_section = "_"
[language.python.settings._]
# See https://github.com/python-lsp/python-lsp-server#configuration
# # pylsp.configurationSources = ["flake8"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"

[language.latex]
filetypes = ["latex"]
roots = [".git"]
command = "texlab"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
offset_encoding = "utf-8"
settings_section = "gopls"

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"
